# 1. 基础配置
baseURL = "https://ks4four.github.io/life/"
theme = 'hugo-bearblog'
title = "Ksfour's Life" # 网站的总标题，可以被各语言覆盖
enableRobotsTXT = true

# 2. 开启多语言模式，并设置中文为默认语言
defaultContentLanguage = "zh"

# 3. 通用参数 (所有语言共享)
[params]
  author = "Ksfour"
  copyright = "Copyright © 2025, Ksfour."
  description = "Ksfour's personal blog"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  # enablePostNavigator = true # 如果需要文章导航，可以取消这行注释

# 4. 针对不同语言的详细配置
[languages]
  # 中文版配置
  [languages.zh]
    languageCode = "zh-CN"
    languageName = "简体中文"
    weight = 1
    title = "Ksfour's Life" # 中文网站的标题
    # 中文版的导航菜单
    [[languages.zh.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
    [[languages.zh.menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 100
    [[languages.zh.menu.main]]
      name = "Opinion"
      url = "/opinion/"
      weight = 101

  # 英文版配置
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 2
    title = "Ksfour's Life" # 英文网站的标题
    # 英文版的导航菜单
    [[languages.en.menu.main]]
      name = "Home"
      url = "/en/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Blog"
      url = "/en/blog/"
      weight = 100
    [[languages.en.menu.main]]
      name = "Opinion"
      url = "/en/opinion/"
      weight = 101

# 5. 修正和简化的配置
# 我们暂时移除了 disableKinds 和 permalinks 来解决核心问题。
# 让 Hugo 默认处理 URL 和页面类型是最稳妥的方式。
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true